[display]
code_editor_font_size = 14
reference_highlighting = false
cell_output = "below"
default_width = "full"
default_table_max_columns = 50
theme = "dark"
default_table_page_size = 10
dataframes = "rich"

[package_management]
manager = "uv"

[runtime]
auto_reload = "off"
watcher_on_save = "lazy"
output_max_bytes = 8000000
auto_instantiate = true
default_auto_download = []
std_stream_max_bytes = 1000000
reactive_tests = true
on_cell_change = "autorun"
default_sql_output = "auto"

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[keymap]
preset = "vim"
destructive_delete = true

[keymap.overrides]

[formatting]
line_length = 65

[diagnostics]
sql_linter = true

[snippets]
include_default_snippets = true
custom_paths = []

[datasources]

[mcp]
presets = []

[mcp.mcpServers]

[ai]
rules = ""
inline_tooltip = false
mode = "manual"

[ai.models]
chat_model = "google/gemini-3-pro-preview"
displayed_models = []
custom_models = []
edit_model = "google/gemini-3-pro-preview"

[server]
browser = "default"
follow_symlink = false

[experimental]

[completion]
copilot = false
activate_on_typing = true

[language_servers.ty]

[language_servers.pylsp]
enable_ruff = true
enable_flake8 = false
enable_pyflakes = false
enabled = true
enable_pydocstyle = false
enable_pylint = false
enable_mypy = true

[language_servers.basedpyright]
